SystematicLR/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using System.Net.Http;
using SystematicLR.GlobalFramework;
using SystematicLR.Entities;
using System.Net;
using SystematicLR.GoogleScholar;
using SystematicLR.Models;
using SystematicLR.Core.Managers;
using SystematicLR.Entities.Model;

namespace SystematicLR.Controllers
{
    [LoginAuth]
    public class ReferenceController : BaseController
    {

        // GET: Reference
        [Active(TreeViewEnum.treeDocuments, SubTreeEnum.NewRef)]
        [Repository]
        public ActionResult Index(string refId)
        {
            if (refId == null)
            {
                ViewBag.SubTitle = "Add New";
                return View();
            }
            else
            {
                ViewBag.SubTitle = "Read";
                ViewBag.ReferenceGUID = refId.ToUpper();
            }
            return View();
        }
        private byte[] GetBytesFromFile(string fullFilePath)
        {
            System.IO.FileStream fs = null;
            try
            {
                fs = System.IO.File.OpenRead(fullFilePath);
                byte[] bytes = new byte[fs.Length];
                fs.Read(bytes, 0, Convert.ToInt32(fs.Length));
                return bytes;
            }
            finally
            {
                if (fs != null)
                {
                    fs.Close();
                    fs.Dispose();
                }
            }
        }
        [Active(TreeViewEnum.treeDocuments, SubTreeEnum.RepContent)]
        [Repository]
        public ActionResult RepositoryContent()
        {
            var Categories = DBServices.GetOptions(CurrentRepository.RepositoryId, "Category");
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem() { Text = "-- Any --", Value = "" });
            items.AddRange(Categories.Select(e => new SelectListItem() { Text = e, Value = e }).ToList());
            ViewBag.Repository = CurrentRepository.RepositoryName;
            ViewBag.Category = items;
            return View();
        }

        public ActionResult SearchReferences(string title, string Category, string referenceId, string isUse, string Bookmark)
        {
            try
            {
                Guid referenceGUIDTemp;
                Guid? referenceGUIDValue = null;
                bool tmp;
                bool? inUse = null;
                bool? bookmark = null;
                if (bool.TryParse(isUse, out tmp))
                    inUse = tmp;
                if (bool.TryParse(Bookmark, out tmp))
                    bookmark = tmp;
                if (Guid.TryParse(referenceId, out referenceGUIDTemp))
                    referenceGUIDValue = referenceGUIDTemp;

                var results = DBServices.GetReferencesByRepositoryGUID(this.ClientUser.UserId, this.CurrentRepository.ReposotoryGUID, string.IsNullOrEmpty(title.Trim()) ? null : title.Trim(), string.IsNullOrEmpty(Category.Trim()) ? null : Category.Trim(), referenceGUIDValue, inUse, bookmark);
                return PartialView("_referencesResults", results);
            }
            catch (Exception ex)
            {
                SystematicLR.GlobalFramework.GlobalMessage msg = new GlobalMessage()
                {
                    Message = "Error During Search Process : <br/> " + ex.Message,
                    MessageType = GlobalMessageType.error
                };
                return Content(msg.RenderMessage().ToString());

            }

        }
        public ActionResult DownloadReference(string refId)
        {
            try
            {
                Guid refGUID;

                if (Guid.TryParse(refId, out refGUID))
                {
                    var document = DBServices.GetReferencePathByGuid(refGUID, this.ClientUser.UserId, this.CurrentRepository.ReposotoryGUID);
                    var parentpath = Server.MapPath("~/App_Data/" + document);
                    if (System.IO.File.Exists(parentpath))
                    {

                        byte[] pdfByte = GetBytesFromFile(parentpath);
                        return File(pdfByte, "application/pdf");
                    }
                    else
                    {
                        return Content("File Not Found");
                    }

                }
            }
            catch (Exception ex)
            {

                return Content(ErrorManager.GetError(ex));

            }
            return null;
        }
        [HttpGet]
        public JsonResult SlidesClick(string Slide, string SlideValue, string refId)
        {
            JSONResponse response = new JSONResponse();
            try
            {
                Guid refGUID;
                bool slideValue = bool.Parse(SlideValue);
                if (Guid.TryParse(refId, out refGUID))
                {
                    if (Slide == "InUse")
                    {
                        DBServices.ChangeIsInUse(refGUID, this.CurrentRepository.ReposotoryGUID, slideValue);
                        if (slideValue)
                            response.message = "The reference has been marked as 'in Use'";
                        else
                            response.message = "The reference has been marked as 'not in Use'";


                    }
                    else if (Slide == "Bookmark")
                    {
                        DBServices.ChangeBookMark(refGUID, this.CurrentRepository.ReposotoryGUID, slideValue);
                        if (slideValue)
                            response.message = "the bookmark has been added to the reference";
                        else
                            response.message = "the bookmark has been Removed from the reference";

                    }
                    else
                    {
                        response.isSuccess = false;
                        response.message = "Invalid request";
                        response.showMessage = true;

                    }
                    response.isSuccess = true;
                    response.showMessage = true;

                }
                else
                {
                    response.isSuccess = false;
                    response.message = "Invalid Reference Id";
                    response.showMessage = true;
                }
            }
            catch (Exception ex)
            {
                response.isSuccess = false;
                response.message = "Error";
                response.showMessage = true;
            }
            return Json(response, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GetReferenceData(string refId, string repId)
        {
            JSONResponse response = new JSONResponse();
            try
            {
                Guid refGUID;

                if (Guid.TryParse(refId, out refGUID) || refId.Length == 8)
                {
                    Guid repository = this.CurrentRepository.ReposotoryGUID;
                    Entities.Model.GetReferenceByGuid_Result document = null;
                    document = refGUID != Guid.Empty ? DBServices.GetReferenceByGuid(refGUID, this.ClientUser.UserId, repository) : DBServices.GetReferenceByGuid(refId, this.ClientUser.UserId, repository);
                    if (document == null)
                    {
                        response.isSuccess = false;
                        response.message = "Reference not found or invalid Id";
                        response.showMessage = true;

                    }
                    else
                    {
                        response.isSuccess = true;
                        response.returndValue = document;
                    }

                }

                else
                {
                    response.isSuccess = false;
                    response.message = "Invalid Reference Id";
                    response.showMessage = true;
                }

            }
            catch (Exception ex)
            {
                response.isSuccess = false;
                response.message = "Reference not found or invalid Id";
                response.showMessage = true;
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetCountries()
        {
            var countries = DBServices.GetOptions(CurrentRepository.RepositoryId, "Country");
            return Json(countries, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetPublishers()
        {
            var options = DBServices.GetOptions(CurrentRepository.RepositoryId, "Publisher", 100);
            return Json(options, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetReferenceTypes()
        {
            var options = DBServices.GetOptions(CurrentRepository.RepositoryId, "ReferenceType");
            return Json(options, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetCategories()
        {
            var options = DBServices.GetOptions(CurrentRepository.RepositoryId, "Category");
            return Json(options, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetDatabases()
        {
            var options = DBServices.GetOptions(CurrentRepository.RepositoryId, "Database");
            return Json(options, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GoogleScholarSearch(string SearchText)
        {
            var output = GoogleScholarManager.SearchArticle(SearchText);
            return PartialView("_GoogleScholarResults", output);
        }
        [HttpGet]
        public ActionResult GoogleScholarCitation(string citaionId)
        {

SystematicLR/Views/Reference/CallGoogleShcolar.cshtml
@{
    ViewBag.Title = "CallGoogleShcolar";
    Layout = "~/Views/Shared/__Layout.cshtml";
}

<h2>CallGoogleShcolar</h2>

<form>
    <iframe src="https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConvert.htm"></iframe>

    <input type="submit" />
</form>

SystematicLR/Views/Reference/GenerateReference.cshtml
@model List<SystematicLR.Entities.Model.GenerateReference_Result>
@{
    ViewBag.Title = "Generate Reference";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<div id="DvDocumentMD" class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">References Section</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        <div class="row">
            <!-- /.box-header -->
            <!-- form start -->
            <div role="form">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">

                            @foreach (var item in Model)
                            {
                                @*<tr><td>[@item.ShortGuid</td>
                                    <td>@Html.Raw(item.Citation)</td></tr>*@
                                <div class="col-md-2">
                                    <span><b><a href="@ViewBag.Link&refId=@item.ShortGuid" target="_blank">[@item.ShortGuid]</a></b></span>
                                </div>
                                <div class="col-md-10" style="margin-bottom:20px">
                                    @if (string.IsNullOrEmpty(item.Citation))
                                    {
                                        <span style="color:red">Citation Not Found</span>                            <a href="index?refId=@item.ReferenceGUID" target="_blank">View</a>
                                    }
                                    else

                                    {
                                        <span>@Html.Raw(item.Citation)</span>
                                    }

                                </div>


                            }

                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

            </div>

            <!-- /.form-group -->


        </div>
        <!-- /.row -->
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="">

    </div>
</div>

SystematicLR/Views/Reference/RepositoryContent.cshtml
@{
    ViewBag.Title = "Repository Contents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section StartScripts{
    <link href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet" />
}
<br />
<div class="row">
    <div class="col-md-12">
        <div id="DvDocumentMD" class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Search..</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                <div class="row">
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div role="form">
                        <div class="box-body">   
                            <div class="row">
                                <div class="col-xs-10">
                                   
                                    <div class="form-group">
                                        <label for="txDocumentTitle">Document Title</label>
                                        <input type="text" class="form-control" id="txDocumentTitle" name="Title">
                                    </div>
                                </div>   
                                <div class="col-xs-1">                                    
                                    <div class="form-group">
                                        <div>
                                            <label>in Use</label>
                                            <select id="ddlInUse" class="form-control">
                                                <option value="" selected>--All--</option>
                                                <option value="true">Yes</option>
                                                <option value="false">No</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>   
                                <div class="col-xs-1">

                                    <div class="form-group">
                                        <div>
                                            <label for="ddlbookMark">Bookmark</label>
                                            <select id="ddlbookMark" class="form-control">
                                                <option value="" selected>--All--</option>
                                                <option value="true">Yes</option>
                                                <option value="false">No</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>                               
                            </div>                        
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="txRefId">Reference ID</label>
                                        <input type="text" class="form-control" id="txRefId" name="txRefId">
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">                                        
                                        <label for="txCategory">Category</label>
                                        @Html.DropDownList("txCategory",(List<SelectListItem>)ViewBag.Category,new {id= "txCategory",@class="form-control" })                                       
                                    </div>
                                </div>
                            </div>


                        </div>
                        <!-- /.box-body -->

                    </div>

                    <!-- /.form-group -->


                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer" style="">
                <button type="button" class="btn btn-info pull-right" onclick="search();">Search</button>
                @*<div class="row" dir="rtl">
                    <div class="col-md-11" ></div>
                        <div class="col-md-1">
                            
                        </div>
                    </div>*@
                
                
            </div>
        </div>
    </div>
</div>
<div id="DVSearchResults"></div>
@section EndScripts
{

    
    <!-- page script -->
    <script>
       
        function search() {
            LoadingStart();
                  
            var Category=$('#txCategory').val();
            var title= $('#txDocumentTitle').val();
            var referenceId = $('#txRefId').val();
            var InUse = $('#ddlInUse').val();
            var bookmark = $('#ddlbookMark').val();
                       
            $.ajax({
                type: "GET",
                url: '@Url.Action("SearchReferences", "Reference")',                
                data: { Category: Category, referenceId: referenceId, title: title ,isUse:InUse,Bookmark:bookmark},                
                success: function (result) {                    
                    $('#DVSearchResults').html(result);
                    
                },
                error: function(xhr, status, error) {                  
                    alert(error);
                },
                complete:function()
                {
                    LoadingFinish();
                }

            });
        }
    </script>
}

SystematicLR/Views/Reference/Search.cshtml
@{
    ViewBag.Title = "Similarity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section StartScripts{
    <link href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Style/switch.css" rel="stylesheet" />
}

<br />
<div class="row" ng-app="">
    <div class="col-md-12">
        <div id="DvDocumentMD" class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Search..</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                <div class="row">
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div role="form">
                        <div class="box-body">   
                            <div class="row">
                                <div class="col-xs-3">
                                   
                                    <div class="form-group">
                                        <label>Term</label>                                        
                                    </div>
                                </div>   
                                <div class="col-xs-3">

                                    <div class="form-group">
                                        <label>Threshold</label>
                                    </div>
                                </div>  
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <div>
                                            <label>TF</label>
                                            <label class="switch">
                                                <input type="checkbox" id="ckbookMark">
                                                <span class="slider round"></span>
                                            </label>
                                            <label>TFBMTF</label>
                                        </div>
                                    </div>
                                </div>                                
                                                         
                            </div>                        
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="form-group">                                        
                                        <input type="text" class="form-control" id="txTerm1" name="txTerm1">
                                    </div>
                                </div>
                                <div class="col-xs-2">
                                    <div class="form-group">    
                                        <input type="range" style="vertical-align:middle;" id="rgthreshold1" value="40" max="100" min="0" ng-model="rg1">                                                                                                             
                                    </div>
                                </div>
                                <div class="col-xs-1">
                                    <div class="form-group">
                                       <span id="thresholdval1"  style="font-weight:bold">{{ rg1 }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="txTerm2" name="txTerm2">
                                    </div>
                                </div>
                                <div class="col-xs-2">
                                    <div class="form-group">
                                        <input type="range" style="vertical-align:middle;" id="rgthreshold2" value="0" max="100" min="0" ng-model="rg2">
                                    </div>
                                </div>
                                <div class="col-xs-1">
                                    <div class="form-group">
                                        <span id="thresholdval2" style="font-weight:bold">{{ rg2 }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="txTerm3" name="txTerm3">
                                    </div>
                                </div>
                                <div class="col-xs-2">
                                    <div class="form-group">
                                        <input type="range" style="vertical-align:middle;" id="rgthreshold3" value="0" max="100" min="0" ng-model="rg3">
                                    </div>
                                </div>
                                <div class="col-xs-1">
                                    <div class="form-group">
                                        <span id="thresholdval3" style="font-weight:bold">{{ rg3 }}</span>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <!-- /.box-body -->

                    </div>

                    <!-- /.form-group -->


                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer" style="">
                <button type="button" class="btn btn-info pull-right" onclick="search();">Search</button>
                @*<div class="row" dir="rtl">
                    <div class="col-md-11" ></div>
                        <div class="col-md-1">
                            
                        </div>
                    </div>*@
                
                
            </div>
        </div>
    </div>
</div>
<div id="DVSearchResults"></div>
@section EndScripts
{

    
    <!-- page script -->
    <script>
       
        function search() {
            LoadingStart();
                  
            var str1 = $('#txTerm1').val();
            var str2 = $('#txTerm2').val();
            var str3 = $('#txTerm3').val();
            var threshold1 = $('#rgthreshold1').val();
            var threshold2 = $('#rgthreshold2').val();
            var threshold3 = $('#rgthreshold3').val();
            var TFBMFT = document.getElementById("ckbookMark").checked;
                       
            $.ajax({
                type: "GET",
                url: '@Url.Action("Similarity", "Reference")',                
                data: { isTFBMTF: TFBMFT, str1: str1,str2:str2,str3:str3, threshold1:threshold1,threshold2:threshold2, threshold3:threshold3},
                success: function (result) {                    
                    $('#DVSearchResults').html(result);
                    
                },
                error: function(xhr, status, error) {                  
                    alert(error);
                },
                complete:function()
                {
                    LoadingFinish();
                }

            });
        }
    </script>
}

SystematicLR/Views/Reference/_GoogleScholarResults.cshtml
@model List<SystematicLR.GoogleScholar.GSOutputArticle>

@if (Model != null)
{
    int i = 0;
    foreach (var art in Model)
    {
        <div class="box box-widget" id="dvGSOut_@i">
            <div class="box-header with-border">
                <div class="user-block">
                    <span class="username" style="margin-left:0px !important"><a href="@art.MainURL" target="_blank" id="hdGSLink">@Html.Raw(art.OrginalArticle.Title)</a></span>
                    <span class="description" style="margin-left:0px !important;color: green;">@Html.Raw(art.OrginalArticle.AuthersSection)</span>
                </div>
                <!-- /.user-block -->
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                <!-- post text -->
                @Html.Raw(art.OrginalArticle.Abstract)
                <br />
                <!-- Social sharing buttons -->
                @if (art.OrginalArticle.ExtraInfo != null && art.OrginalArticle.ExtraInfo.file != null)
                {
                    <a href="@art.DownloadURL" class="btn btn-default btn-xs" target="_blank" id="hdDownload">
                        <i class="fa fa-share"></i>
                        @art.OrginalArticle.ExtraInfo.file.Label
                    </a>
                }
                else
                {
                    <a href = "@art.MainURL" class="btn btn-default btn-xs" target="_blank" id="hdDownload">
                        <i class="fa fa-share"></i>
                        @art.HostSite
                    </a>
                }
                <button type="button" class="btn btn-success btn-xs" onclick="GSChoose(this);"><i class="fa fa-thumbs-o-up"></i> Want This</button>
                <span class="pull-right text-muted">Cited By @art.CitedBy - @art.Versions Versions</span>
                <input type="hidden" id="hdTitle" value="@art.Title" />
                <input type="hidden" id="hdAbstract" value="@art.Abstarct" />
                <input type="hidden" id="hdAuthers" value="@art.Authers" />
                <input type="hidden" id="hdPublisher" value="@art.Publisher" />
                <input type="hidden" id="hdYear" value="@art.Year" />
                <input type="hidden" id="hdHost" value="@art.HostSite" />
                <input type="hidden" id="hdCitedBy" value="@art.CitedBy" />
                <input type="hidden" id="hdVersions" value="@art.Versions" />
                <input type="hidden" id="hdCitedByLink" value="@art.CitedByLink" />
                <input type="hidden" id="hdCiteId" value="@art.CiteId" />
                <input type="hidden" id="hdFileType" value="@art.FileType" />
                <input type="hidden" id="hdRelatedArticlesLink" value="@art.RelatedArticlesLink" />
                <input type="hidden" id="hdVersionLink" value="@art.VersionLink" />
                <input type="hidden" id="hdVersions" value="@art.Versions" />
            </div>
        </div>

    }
}